export const DEFAULT_STATIC = {
    VALID_IMAGE_SIZE: 800000,
    DESKTOP_IMAGE_VALID_DIMENSIONS: {
        VALID_WIDTH: 2340,
        VALID_HEIGHT: 700,
    },
    TABLET_IMAGE_VALID_DIMENSIONS: {
        VALID_WIDTH: 1440,
        VALID_HEIGHT: 1080,
    },
    MOBILE_IMAGE_VALID_DIMENSIONS: {
        VALID_WIDTH: 1920,
        VALID_HEIGHT: 1080,
    },
}